apiVersion: batch/v1
kind: Job
metadata:
  name: "minio-bucket-job"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-3"
spec:
  template:
    spec:
      serviceAccountName: "minio-bucket"
      containers:
      - name: "bucket-creator"
        image: "docker.io/cengleby86/minio-cli:latest"
        command: ["/bin/bash", "-c"]
        args:
          - |
            mc alias set default https://minio-api-minio-operator.{{ .Values.domain }} ${access_key_id} ${access_key_secret};
            mc mb default/opentelemetry;
        envFrom:
          - secretRef:
              name: minio-credentials
      restartPolicy: Never
