apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret-minio-credentials
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-4"
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    template:
      type: generic
      data:
        endpoint: https://minio-api-minio-operator.${DOMAIN}
        bucket: opentelemetry
        access_key_id: "{{`{{ .MINIO_ROOT_USER }}`}}"
        access_key_secret: "{{`{{ .MINIO_ROOT_PASSWORD }}`}}"
  data:
  - secretKey: MINIO_ROOT_USER
    remoteRef:
      key: "minio"
      property: MINIO_ROOT_USER
  - secretKey: MINIO_ROOT_PASSWORD
    remoteRef:
      key: "minio"
      property: MINIO_ROOT_PASSWORD