apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: container-build-pipeline
spec:
  params:
    - name: IMAGE_NAME
    - name: REGISTRY_HOSTNAME
    - name: REGISTRY_NAMESPACE
    - name: IMAGE_TAG
    - name: GITHUB_REPO
    - name: GITHUB_BRANCH
  workspaces:
    - name: source
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GITHUB_REPO)
        - name: revision
          value: $(params.GITHUB_BRANCH)
        - name: sslVerify
          value: 'false'
        - name: noProxy
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
      - name: output
        workspace: source

    - name: buildah-build
      params:
        - name: IMAGE
          value: 'quay.io/$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'true'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: source

    - name: buildah-push
      params:
        - name: IMAGE
          value: 'quay.io/$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - buildah-build
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: source
