apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pre-fetch-dependencies
  labels:
    app.kubernetes.io/version: "0.7"
  annotations:
    tekton.dev/categories: Dependencies
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: pre-fetch-dependencies
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
    tekton.dev/displayName: pre-fetch-dependencies
spec:
  description: >-
    Needs Description

  params:
    - name: DIRECTORY
      description: "App directory path in the repo"
      default: ""
    - name: HERMETIC
      default: 'false'
      description: Reference of the image buildah will produce.
  workspaces:
  - name: source
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"

  steps:

    - name: fetch-deps
      image: quay.io/redhat-appstudio/cachi2:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash

        pwd
        git config --global --add safe.directory $(workspaces.source.path)
        ls -la 
        cachi2 --version

        # Define an associative array with file indicators and their corresponding package managers
        declare -A pkg_managers=(
          ["go.mod"]="gomod"
          ["package.json"]="npm"
          ["requirements.txt"]="pip"
          ["yarn.lock"]="yarn"
        )

        # Loop through the array and check for the presence of each file
        for file in "${!pkg_managers[@]}"; do
          if [[ -f "$file" ]]; then
            PKG_TYPE="${pkg_managers[$file]}"
            break
          fi
        done

        # Check if a package manager was determined
        if [[ -z "$PKG_TYPE" ]]; then
          echo "No supported package manager file found."
          exit 1
        fi

        # Fetch dependencies using the determined package manager
        cachi2 fetch-deps $PKG_TYPE --source . --output .
