---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: gitlab-runner-token
spec:
  length: 64
  symbols: 0
  digits: 5
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-secret
spec:
  refreshInterval: "0"
  target:
    name: gitlab-runner-secret
  dataFrom:
  - rewrite:
      - regexp:
          source: "password"
          target: "runner-registration-token"
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: gitlab-runner-token
