apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  chart:
    values:
      certmanager:
        install: true
      certmanager-issuer:
        email: "admin@openshift.com"
      global:
        edition: ce
        hosts:
          domain: "{{ .Values.domain }}"
        appConfig:
          omniauth:
            enabled: true
            providers:
              - name: "openid_connect"
                app_id: "openshift"
                app_secret: "8jeQPF94DJvFRlDNAbHzaxwWOIa9r2nh"
                args:
                  name: "Keycloak"
                  scope: ["openid", "profile", "email", "groups"]
                  response_type: "code"
                  issuer: "https://keycloak-keycloak.apps.nb-demo-01.6jz4.p1.openshiftapps.com/auth/realms/openshift"
                  discovery: true
        ingress:
          class: none
          annotations:
            route.openshift.io/termination: edge
          configureCertmanager: false
          tls:
            secretName: null
    version: "8.4.6"