apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  chart:
    values:
      certmanager:
        install: true
      certmanager-issuer:
        email: "admin@cluster.local"
      global:
        edition: ce
        hosts:
          domain: "{{ .Values.domain }}"
        ingress:
          class: none
          annotations:
            route.openshift.io/termination: edge
          configureCertmanager: false
          tls:
            secretName: null
    version: 7.11.1