apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  chart:
    values:
      certmanager:
        install: true
      certmanager-issuer:
        email: "admin@openshift.com"
      # https://docs.gitlab.com/charts/charts/globals/ for settings
      global:
        edition: ce
        hosts:
          domain: "{{ .Values.domain }}"
        appConfig:
          # https://docs.gitlab.com/integration/omniauth/#configure-common-settings
          omniauth:
            enabled: true
            allowSingleSignOn: ["openid_connect"]
            blockAutoCreatedUsers: false
            autoLinkUser: ['openid_connect']
            providers:
              - secret: keycloak-oidc-client
        runner:
          registrationToken:
            secret: gitlab-runner-secret
        ingress:
          class: none
          annotations:
            route.openshift.io/termination: edge
          configureCertmanager: false
          tls:
            secretName: null
      gitlab-runner:
        install: true
        rbac:
          create: true
        runners:
          locked: false
          secret: gitlab-runner-secret
          config: |
            [[runners]]
              [runners.kubernetes]
              image = "ubuntu:22.04"
    version: "8.4.6"