---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitlab-system
  name: deployment-manager
rules:
- apiGroups: ["external-secrets.io"]
  resources: ["pushsecrets"]
  verbs: ["get", "list", "create", "update"]
- apiGroups: [
    ""
  ]
  resources: [
    "secrets"
  ]
  verbs: [
    "get", 
    "list",
    "create"
  ]
- apiGroups: [
    "apps"
  ]
  resources: [
    "deployments"
  ]
  verbs: [
    "get", 
    "list"
  ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: gitlab-system
subjects:
- kind: ServiceAccount
  name: ansible-runner
  namespace: gitlab-system
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
