---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: self-provisioned-repository
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: development-tools
    template:
      type: generic
      data:
        password: "{{`{{ .password }}`}}"
        username: "{{`{{ .username }}`}}"
        type: git
        url: "{{`{{ .url }}`}}"
        insecure: "true"
        project: default
  data:
    - secretKey: "password"
      remoteRef:
        key: gitlab
        property: token
    - secretKey: "username"
      remoteRef:
        key: repo
        property: username
    - secretKey: "url"
      remoteRef:
        key: repo
        property: url
