apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gitlab-repo-org-credentials
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: gitlab-repo-org-credentials
    template:
      metadata:
        labels:
          # argocd.argoproj.io/secret-type: repository
      type: generic
      data:
        password: "{{`{{ .password }}`}}"
        username: "root"
        type: git
        url: "https://gitlab.{{ .Values.domain }}/self-provisioned"
        project: system
  data:
    - secretKey: "password"
      remoteRef:
        key: gitlab
        property: token
