apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oidc-client
stringData:
  name: "openid_connect"
  app_id: "openshift"
  app_secret: "8jeQPF94DJvFRlDNAbHzaxwWOIa9r2nh"
  args:
    name: "Keycloak"
    scope: ["openid", "profile", "email", "groups"]
    response_type: "code"
    issuer: "https://keycloak-keycloak.apps.nb-demo-01.6jz4.p1.openshiftapps.com/auth/realms/openshift"
    discovery: true