apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oidc-client
stringData:
  provider: |
    name: "openid_connect"
    label: "Keycloak"
    args:
      client_options:
        identifier: "openshift"
        secret: "8jeQPF94DJvFRlDNAbHzaxwWOIa9r2nh"
        issuer: "https://keycloak-keycloak.apps.nb-demo-01.6jz4.p1.openshiftapps.com/auth/realms/openshift"
      scope: ["openid", "profile", "email", "groups"]
      response_type: "code"
      discovery: true