apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oidc-client
stringData:
  provider: |
    name: "openid_connect"
    label: "Keycloak"
    args:
      name: "openid_connect"
      client_options:
        identifier: "openshift"
        secret: "8jeQPF94DJvFRlDNAbHzaxwWOIa9r2nh"
        redirect_uri: "https://gitlab.{{ .Values.domain }}/users/auth/openid_connect/callback"
      scope: ["openid", "profile", "email"]
      response_type: "code"
      issuer: "https://keycloak-keycloak.apps.nb-demo-01.6jz4.p1.openshiftapps.com/auth/realms/openshift"
      discovery: true
      uid_field: "uid"