apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: container-build-pipeline
spec:
  params:
    - name: IMAGE_NAME
    - name: REGISTRY_HOSTNAME
    - name: REGISTRY_NAMESPACE
    - name: IMAGE_TAG
    - name: GITHUB_REPO
    - name: GITHUB_BRANCH
  workspaces:
    - name: source
    - name: containers
    - name: basic-auth
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GITHUB_REPO)
        - name: revision
          value: $(params.GITHUB_BRANCH)
        - name: sslVerify
          value: 'false'
        - name: noProxy
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: source
      - name: basic-auth
        workspace: basic-auth
    - name: container-build
      params:
        - name: IMAGE_NAME
          value: $(params.IMAGE_NAME)
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
      taskRef:
        name: podman-build
      runAfter: 
      - git-clone
      workspaces:
      - workspace: containers
        name: containers
      - workspace: source
        name: source
    - name: container-push
      params:
        - name: IMAGE_NAME
          value: $(params.IMAGE_NAME)
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: REGISTRY_HOSTNAME
          value: $(params.REGISTRY_HOSTNAME)
        - name: REGISTRY_NAMESPACE
          value: $(params.REGISTRY_NAMESPACE)
      taskRef:
        name: podman-push
      runAfter: 
      - container-build
      workspaces:
      - workspace: containers
        name: containers
