apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repository-secret
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: repository-secret
    template:
      type: generic
      data:
        .gitconfig: |
          [credential "https://{{ .Values.hostname }}"]
            helper = store
        .git-credentials: |
          https://{{ .Values.username }}:{{`{{ .token }}`}}@{{ .Values.hostname }}
  data:
  - secretKey: token
    remoteRef:
      key: gitlab
      property: token
