{{ if .Values.machinesets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machine-sets-plugin
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: managed-machine-sets
    server: https://kubernetes.default.svc
  source:
    chart: machinesets
    repoURL: https://poc-examples.github.io/charts
    targetRevision: "{{ .Values.machinesets.chartVersion }}"
    helm:
      valuesObject: {{ toJson .Values.machinesets.helmValues }}
  project: plugins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
