{{ if .Values.gitops.updater.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-plugin
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: "{{ .Values.gitops.namespace }}"
    server: https://kubernetes.default.svc
  source:
    chart: image-updater
    repoURL: https://poc-examples.github.io/charts
    targetRevision: "{{ .Values.gitops.updater.chartVersion }}"
  project: plugins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
