{{ if .Values.acs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "self-provisioner-plugin"
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: "{{ .Values.gitops.namespace }}"
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://gitlab.apps.{{ .Values.domain }}/self-provisioned/manifests"
    path: "applications"
    targetRevision: HEAD
    directory:
      recurse: true
  project: plugins
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}