{{ if .Values.acs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub-plugin
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  source:
    chart: developerhub
    targetRevision: "{{ .Values.devhub.chartVersion }}"
    repoURL: https://poc-examples.github.io/charts
    helm:
      parameters:
        - name: host
          value: "{{ .Values.domain }}"
  project: plugins
  timeout: 120
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
