{{ if .Values.acs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-plugin
  namespace: "{{ .Values.gitops.namespace }}"
spec:
  destination:
    namespace: "{{ .Values.gitlab.namespace }}"
    server: https://kubernetes.default.svc
  source:
    chart: gitlab
    targetRevision: "{{ .Values.gitlab.chartVersion }}"
    repoURL: "https://poc-examples.github.io/charts"
    helm:
      parameters:
        - name: namespace
          value: "{{ .Values.gitlab.namespace }}"
        - name: domain
          value: apps.{{ .Values.domain }}
  project: plugins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
