{{ if .Values.acs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-plugin
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  source:
    chart: keycloak
    repoURL: "https://poc-examples.github.io/charts"
    targetRevision: "{{ .Values.keycloak.chartVersion }}"
    helm:
      valuesObject:
        domain: "{{ .Values.domain }}"
  project: plugins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
