apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: local-cluster
  labels:
    name: local-cluster
    cloud: Azure
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: local
  annotations: {}
spec:
  hubAcceptsClient: true
