apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: boot-policies
spec:
  description: Policy for bootstrapping cluster with intial services
  policies:
    {{- if eq .Values.external_secrets.enabled true }}
    - "external-secrets-operator"
    {{- end }}
    {{- if eq .Values.gatekeeper.enabled true }}
    - "gatekeeper-operator"
    {{- end }}
