apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "acm-policies-plugin"
  namespace: "{{ .Values.gitops.namespace }}"
spec:
  destination:
    namespace: "local-policies"
    server: 'https://kubernetes.default.svc'
  source:
    chart: policies
    repoURL: "https://poc-examples.github.io/charts"
    targetRevision: 0.1.48
    helm:
      parameters:
        - name: domain
          value: "{{ .Values.domain }}"
  project: plugins
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - SyncTimeout=120
