apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: sso
  name: keycloak
spec:
  external:
    enabled: false
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    experimental:
      args:
        - '-Dkeycloak.profile=preview'
        - '-Dkeycloak.profile.feature.token-exchange=enabled'
        - '-Dkeycloak.profile.feature.impersonation=disabled'
  instances: 1
  DisableDefaultServiceMonitor: true
