apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: sso
  name: keycloak
spec:
  # external:
  #   enabled: true
    # url: https://keycloak-keycloak.apps.{{ .Values.domain }}
  externalAccess:
    enabled: true
  instances: 1
