apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
  name: keycloak
spec:
  hostname:
    hostname: keycloak.apps.{{ .Values.domain }}
    adminUrl: https://keycloak.apps.{{ .Values.domain }}
  http:
    httpEnabled: true
  ingress:
    enabled: true
  instances: 1
