apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
  name: keycloak
spec:
  hostname:
    hostname: keycloak.apps.{{ .Values.domain }}
    adminUrl: https://keycloak.apps.{{ .Values.domain }}
  http:
    httpEnabled: true
  ingress:
    enabled: true
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: postgres-credentials
      key: username
    passwordSecret:
      name: postgres-credentials
      key: password