apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: keycloak
spec:
  hostname:
    hostname: keycloak
    admin: keycloak-admin
  http:
    httpEnabled: true
  ingress:
    enabled: true
    className: openshift-default
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: postgres-credentials
      key: username
    passwordSecret:
      name: postgres-credentials
      key: password