# apiVersion: keycloak.org/v1alpha1
# kind: KeycloakUser
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#   name: cengleby
#   namespace: keycloak
#   labels:
#     app: sso
# spec:
#   realmSelector:
#     matchLabels:
#       app: sso
#   user:
#     credentials:
#       - type: password
#         value: MTE3MDI5
#     email: cengleby@redhat.com
#     emailVerified: true
#     enabled: true
#     firstName: Chris
#     lastName: Engleby
#     username: cengleby
