apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
  name: keycloak
spec:
  external:
    enabled: true
    url: keycloak-keycloak.apps.{{ .Values.domain }}
  externalAccess:
    enabled: true
  instances: 1
