apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "keycloak-initial-users"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "kubernetes-secrets-store"
    kind: ClusterSecretStore
  target:
    name: "keycloak-initial-users"
    template:
      type: generic
      data:
        users: "{{`{{ .USER }}`}}"
  data:
    - secretKey: "USERS"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "keycloak-initial-users"
        property: users
