{{- if .Values.shared.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "pull-secret-credential-keycloak"
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-external-secret-store
    kind: ClusterSecretStore
  target:
    name: credential-keycloak
  data:
  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: credential-keycloak
      property: ADMIN_PASSWORD
  - secretKey: ADMIN_USERNAME
    remoteRef:
      key: credential-keycloak
      property: ADMIN_USERNAME
{{- end }}