apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: master
spec:
  keycloakCRName: keycloak
  realm:
    id: master
    realm: master
    displayName: Master
    enabled: true
