apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "rosa-token"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "kubernetes-secrets-store"
    kind: ClusterSecretStore
  target:
    name: "rosa-token"
    template:
      type: generic
      data:
        ROSA_TOKEN: "{{`{{ .ROSA_TOKEN }}`}}"
  data:
    - secretKey: "ROSA_TOKEN"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "rosa-token"
        property: token
