---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    template:
      type: generic
  data:
    - secretKey: "password"
      remoteRef:
        key: keycloak
        property: "password"
    - secretKey: "username"
      remoteRef:
        key: keycloak
        property: "username"
    - secretKey: "database"
      remoteRef:
        key: keycloak
        property: "database"
