# apiVersion: keycloak.org/v1alpha1
# kind: KeycloakUser
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#   name: admin
#   labels:
#     app: sso
#     realm: openshift
# spec:
#   realmSelector:
#     matchLabels:
#       realm: openshift
#   user:
#     credentials:
#       - type: password
#         valueFrom:
#           secretKeyRef:
#             name: keycloak-admin-user
#             key: password
#     email: admin@openshift.com
#     emailVerified: true
#     enabled: true
#     firstName: Chris
#     lastName: Engleby
#     username: admin
