apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  webhook:
    logLevel: INFO
    emitAdmissionEvents: Disabled
  audit:
    auditInterval: '60s'
    logLevel: INFO
  validatingWebhook: Enabled
  mutatingWebhook: Disabled
