apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
  namespace: openshift-operators
spec:
  webhook:
    logLevel: INFO
    emitAdmissionEvents: Disabled
  audit:
    auditInterval: '60'
    logLevel: INFO
  validatingWebhook: Enabled
  mutatingWebhook: Disabled
