kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: dynamic-plugins
  labels:
    app.kubernetes.io/instance: developer-hub
    app.kubernetes.io/name: backstage
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:

      ##############################
      ## KEYCLOAK BACKEND PLUGIN
      ##############################
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic

    {{- if .Values.gitlab.enabled }}
      ##############################
      ## GITLAB PLUGIN CONFIGURATION
      ##############################
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab
    {{- end }}

      ##################################
      ## DYNAMIC HOME PAGE PLUGIN CONFIGURATION
      ## https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/customizing_red_hat_developer_hub/customizing-the-home-page
      ##################################
      - disabled: false
        package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-dynamic-home-page

      ####################################
      ## RED HAT RBAC PLUGIN CONFIGURATION
      ## https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/authorization_in_red_hat_developer_hub/enabling-and-giving-access-to-rbac
      ####################################
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-community-plugin-rbac

      # ##################################
      # ## NOTIFICATIONS PLUGIN CONFIGURATION
      # ## https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/customizing_red_hat_developer_hub/customizing-the-home-page
      # ##################################
      # - disabled: false
      #   package: "./dynamic-plugins/dist/backstage-plugin-notifications"
      # - disabled: false
      #   package: "./dynamic-plugins/dist/backstage-plugin-notifications-backend-dynamic"

      # ##################################
      # ## SIGNALS PLUGIN CONFIGURATION
      # ## https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/customizing_red_hat_developer_hub/customizing-the-home-page
      # ##################################
      # - disabled: false
      #   package: "./dynamic-plugins/dist/backstage-plugin-signals"
      # - disabled: false
      #   package: "./dynamic-plugins/dist/backstage-plugin-signals-backend-dynamic"

      ##################################
      ## ORCHESTRATOR PLUGIN CONFIGURATION
      ## https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/customizing_red_hat_developer_hub/customizing-the-home-page
      ##################################
      - disabled: false
        package: "https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator-backend-dynamic/-/backstage-plugin-orchestrator-backend-dynamic-1.6.0.tgz"
        integrity: sha512-Kr55YbuVwEADwGef9o9wyimcgHmiwehPeAtVHa9g2RQYoSPEa6BeOlaPzB6W5Ke3M2bN/0j0XXtpLuvrlXQogA==
        pluginConfig:
          orchestrator:
            dataIndexService:
              url: http://backstage-sonataflow-platform-data-index-service.backstage.svc.cluster.local
      - disabled: false
        package: "https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator/-/backstage-plugin-orchestrator-1.6.0.tgz"
        integrity: sha512-fOSJv2PgtD2urKwBM7p9W6gV/0UIHSf4pkZ9V/wQO0eg0Zi5Mys/CL1ba3nO9x9l84MX11UBZ2r7PPVJPrmOtw==
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-orchestrator:
                appIcons:
                  - importName: OrchestratorIcon
                    name: orchestratorIcon
                dynamicRoutes:
                  - importName: OrchestratorPage
                    menuItem:
                      icon: orchestratorIcon
                      text: Orchestrator
                    path: /orchestrator
      - disabled: false
        package: "https://npm.registry.redhat.com/@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic/-/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic-1.6.0.tgz"
        integrity: sha512-Bueeix4661fXEnfJ9y31Yw91LXJgw6hJUG7lPVdESCi9VwBCjDB9Rm8u2yPqP8sriwr0OMtKtqD+Odn3LOPyVw==
        pluginConfig:
          orchestrator:
            dataIndexService:
              url: http://backstage-sonataflow-platform-data-index-service.backstage.svc.cluster.local
      - disabled: false
        package: "https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator-form-widgets/-/backstage-plugin-orchestrator-form-widgets-1.6.0.tgz"
        integrity: sha512-Tqn6HO21Q1TQ7TFUoRhwBVCtSBzbQYz+OaanzzIB0R24O6YtVx3wR7Chtr5TzC05Vz5GkBO1+FZid8BKpqljgA==
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-orchestrator-form-widgets: {}

      ##############################
      ## TEKTON PLUGIN CONFIGURATION
      ##############################
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-community-plugin-tekton
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage-community.plugin-tekton:
                mountPoints:
                  - mountPoint: entity.page.ci/cards
                    importName: TektonCI
                    config:
                      layout:
                        gridColumn: "1 / -1"
                      if:
                        allOf:
                          - isTektonCIAvailable

      ##################################
      ## TECH RADAR PLUGIN CONFIGURATION
      ##################################
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic

      ###############################
      ## ARGOCD PLUGIN CONFIGURATION
      ###############################
      - disabled: false
        package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd

      ##################################
      ## KUBERNETES PLUGIN CONFIGURATION
      ##################################
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-kubernetes

      ##################################
      ## TOPOLOGY PLUGIN CONFIGURATION
      ##################################
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-community-plugin-topology
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage-community.plugin-topology:
                mountPoints:
                  - mountPoint: entity.page.topology/cards
                    importName: TopologyPage
                    config:
                      layout:
                        gridColumn: "1 / -1"
                        height: 75vh
                      if:
                        anyOf:
                          - hasAnnotation: backstage.io/kubernetes-id
                          - hasAnnotation: backstage.io/kubernetes-namespace
