apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditional-policies
data:
  policies.yaml: |
    result: CONDITIONAL
    roleEntityRef: role:default/cluster-admins
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      rule: HAS_SPEC
      resourceType: catalog-entity
      params:
        key: type
        value: service
