{{ if .Values.orchestrator.postgres.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orchestrator-postgres-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
{{ end }}