apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: boot-policies
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  description: Policy for bootstrapping cluster with intial services
  policies:
    - "services"
