apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  name: developers
rules:
- apiGroups:
    - opentelemetry.io
  resources:
    - opentelemetrycollectors
    - instrumentations
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
- apiGroups:
    - image.openshift.io
  resources:
    - imagestreams
    - imagestreamimports
    - imagestreamimages
    - imagestreamtags
  verbs:
    - create
    - get
    - list
    - delete
    - update
- apiGroups:
    - build.openshift.io
  resources:
    - buildconfigs
    - builds
    - buildconfigs/instantiatebinary
  verbs:
    - create
    - get
    - list
    - delete
    - update
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - create
    - get
    - list
    - update
    - delete
- apiGroups:
    - batch
  resources:
    - cronjobs
    - jobs
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - delete
- apiGroups:
    - serving.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - services
    - revisions
    - routes
- apiGroups:
    - sources.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - apiserversources
- apiGroups:
    - eventing.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - brokers
    - triggers
- apiGroups:
    - messaging.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - channels
    - subscriptions
- apiGroups:
    - operators.coreos.com
  verbs:
    - get
    - list
  resources:
    - clusterserviceversions
- apiGroups:
    - operator.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - knativeservings
    - knativeeventings
- apiGroups:
    - operator.serverless.openshift.io
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - knativekafkas
- verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  apiGroups:
    - kafka.strimzi.io
  resources:
    - kafkanodepools
    - kafkaconnects
    - kafkabridges
    - kafkatopics
    - kafkausers
    - kafkaconnectors
    - kafkamirrormaker2s
    - kafkarebalances
    - kafkas
