apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: backstage-app-config
        - name: backstage-backend-config
        - name: tech-radar-plugin
        - name: catalog-config
        - name: kubernetes-plugin
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
      secrets:
        - name: gitlab-token
          key: GITLAB_TOKEN
        - name: backend-credentials
          key: DEVHUB_BACKEND_SECRET
        - name: argocd-token
          key: ARGOCD_TOKEN
    dynamicPluginsConfigMapName: dynamic-plugins
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
