kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: dynamic-plugins
  labels:
    app.kubernetes.io/instance: developer-hub
    app.kubernetes.io/name: backstage
    rhdh.redhat.com/app: backstage-developer-hub
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - disabled: false
        package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab
      - disabled: false
        package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic

      ##########################
      ## TECH DOCS CONFIGURATION
      ##########################
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-techdocs
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-techdocs:
                routeBindings:
                  targets:
                    - importName: techdocsPlugin
                  bindings:
                    - bindTarget: catalogPlugin.externalRoutes
                      bindMap:
                        viewTechDoc: techdocsPlugin.routes.docRoot
                    - bindTarget: scaffolderPlugin.externalRoutes
                      bindMap:
                        viewTechDoc: techdocsPlugin.routes.docRoot
                dynamicRoutes:
                  - path: /docs
                    importName: TechDocsIndexPage
                    menuItem:
                      icon: docs
                      text: Docs
                  - path: /docs/:namespace/:kind/:name/*
                    importName: TechDocsReaderPage
                mountPoints:
                  - mountPoint: entity.page.docs/cards
                    importName: EntityTechdocsContent
                    config:
                      layout:
                        gridColumn: "1 / -1"
                      if:
                        allOf:
                          - isTechDocsAvailable
                  - mountPoint: search.page.results
                    importName: TechDocsSearchResultListItem
                  - mountPoint: search.page.filters
                    importName: TechdocsSearchFilter
                  - mountPoint: search.page.types
                    importName: techdocsSearchType
                    config:
                      props:
                        name: Documentation
                        icon: docs

      ##############################
      ## TEKTON PLUGIN CONFIGURATION
      ##############################
      - disabled: false
        package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton
        pluginConfig:
          dynamicPlugins:
            frontend:
              janus-idp.backstage-plugin-tekton:
                mountPoints:
                - config:
                    if:
                      allOf:
                      - isTektonCIAvailable
                    layout:
                      gridColumn: 1 / -1
                      gridRowStart: 1
                  importName: TektonCI
                  mountPoint: entity.page.ci/cards

      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-tech-radar
      - disabled: false
        package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
      ## Maybe
      ## @roadiehq/scaffolder-backend-module-utils
