kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-plugin
data:
  kubernetes-plugin.yaml: |
    kubernetes:
      clusterLocatorMethods:
        - type: config
          clusters:
            - authProvider: serviceAccount
              name: demo-cluster
              skipTLSVerify: true
              serviceAccountToken: ${token}
              url: https://api.{{ .Values.host }}:6443
      customResources:
        - apiVersion: v1beta1
          group: tekton.dev
          plural: pipelineruns
        - apiVersion: v1beta1
          group: tekton.dev
          plural: taskruns
        - apiVersion: v1
          group: route.openshift.io
          plural: routes
      serviceLocatorMethod:
        type: multiTenant
