apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-credentials
  data:
  - secretKey: KEYCLOAK_PASSWORD
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: credential-keycloak
      property: ADMIN_PASSWORD
  - secretKey: KEYCLOAK_USERNAME
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: credential-keycloak
      property: ADMIN_USERNAME