apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-admin
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: gitlab-credentials
  data:
  - secretKey: GITLAB_PASSWORD
    remoteRef:
      key: gitlab
      property: token