gitlab:
  upgradeCheck:
    enabled: false
  certmanager:
    install: false
  certmanager-issuer:
    email: admin@openshift.com
  global:
    edition: ce
    hosts:
      domain: apps.{{ .Values.domain }}
  ingress:
    class: none
    annotations:
      route.openshift.io/termination: edge
    configureCertmanager: false
    tls:
      secretName: null
