{{ if .Values.gitlab.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-service
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    chart: cert-manager
    repoURL: https://poc-examples.github.io/charts
    targetRevision: "0.1.0"
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
