{{ if .Values.external_secrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-service
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  source:
    chart: external_secrets
    repoURL: https://poc-examples.github.io/charts
    targetRevision: "{{ .Values.external_secrets.chartVersion }}"
    helm:
      valuesObject:
        namespace: "{{ .Values.external_secrets.namespace }}"
        gitops:
            namespace: "{{ .Values.gitops.namespace }}"
        subscription:
            channel: stable
        vault:
          enabled: "{{ .Values.vault.enabled }}"
          address: "{{ .Values.vault.address }}"
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
