{{ if .Values.nvidiagpu.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-service
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: nvidia-gpu-operator
    server: https://kubernetes.default.svc
  source:
    chart: nvidia-gpu-operator
    repoURL: https://poc-examples.github.io/charts
    targetRevision: "{{ .Values.nvidiagpu.chartVersion }}"
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
