{{ if .Values.tekton.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tekton-appset
  namespace: "{{ .Values.gitops.namespace }}"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: default
  template:
    metadata:
      name: tekton-service
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
    spec:
      destination:
        namespace: "openshift-pipelines"
        server: https://kubernetes.default.svc
      source:
        chart: tekton
        targetRevision: "{{ .Values.tekton.chartVersion }}"
        repoURL: "https://poc-examples.github.io/charts"
        helm:
          parameters:
            - name: domain
              value: "{{ `{{ .metadata.labels.domain }}` }}"
            - name: chains.enabled
              value: "{{ .Values.chains.enabled }}"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
{{ end }}
