{{ if .Values.tekton.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-service
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: "openshift-operators"
    server: https://kubernetes.default.svc
  source:
    chart: tekton
    targetRevision: "{{ .Values.tekton.chartVersion }}"
    repoURL: "https://poc-examples.github.io/charts"
    helm:
      parameters:
        - name: domain
          value: "{{ .Values.domain }}"
        - name: chains.enabled
          value: {{ .Values.chains.enabled }}
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
