# {{ if .Values.acs.enabled }}
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: advanced-cluster-security-service
#   namespace: "{{ .Values.gitops.namespace }}"
#   annotations:
#     argocd.argoproj.io/sync-wave: "-4"
# spec:
#   destination:
#     namespace: rhacs-operator
#     server: https://kubernetes.default.svc
#   source:
#     chart: acs
#     repoURL: https://poc-examples.github.io/charts
#     targetRevision: "{{ .Values.acs.chartVersion }}"
#   project: system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     managedNamespaceMetadata:
#       labels:
#         argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
#     syncOptions:
#       - CreateNamespace=true
#       - Validate=false
# {{ end }}
