{{ if .Values.external_secrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-connectors-service
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  destination:
    namespace: secrets-connectors
    server: https://kubernetes.default.svc
  source:
    chart: external-secrets-connectors
    repoURL: https://poc-examples.github.io/charts
    targetRevision: "{{ .Values.external_secrets.connectors.chartVersion }}"
    helm:
      ## ONLY VAULT IS CURRENTLY AVAILABLE
      ## WILL ADD ADDITIONAL CONNECTORS IN FUTURE AS USE CASES GET RAISED
      valuesObject:
        vault:
          enabled: "{{ .Values.vault.enabled }}"
          address: "{{ .Values.vault.address }}"
        k8s:
          enabled: "{{ .Values.external_secrets.k8sConnector.enabled }}"
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
