{{ if .Values.servicemesh.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemesh-service
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  destination:
    namespace: openshift-servicemesh
    server: https://kubernetes.default.svc
  source:
    chart: servicemesh
    targetRevision: "{{ .Values.servicemesh.chartVersion }}"
    repoURL: 'https://poc-examples.github.io/charts'
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
