# {{ if .Values.gitlab.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-config
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: "{{ .Values.gitlab.namespace }}"
    server: https://kubernetes.default.svc
  source:
    chart: ansible-sidecar
    targetRevision: "{{ .Values.gitlab.chartVersion }}"
    repoURL: "https://poc-examples.github.io/charts"
    helm:
      parameters:
        - name: domain
          value: apps.{{ .Values.domain }}
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
# {{ end }}
