{{ if .Values.gitlab.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitlab-config-appset
  namespace: "{{ .Values.gitops.namespace }}"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: default
  template:
    metadata:
      name: gitlab-config
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
    spec:
      destination:
        namespace: "{{ .Values.gitlab.namespace }}"
        server: https://kubernetes.default.svc
      source:
        chart: ansible-runner
        targetRevision: "0.2.1"
        repoURL: "https://poc-examples.github.io/supporting-charts"
        helm:
          parameters:
            - name: runner.name
              value: gitlab-configure
            - name: runner.namespace
              value: gitlab-system
          valuesObject:
            scope: ClusterRole
            additionalVars:
              domain: "{{ `{{ .metadata.labels.domain }}` }}"
            rules:
              - apiGroups:
                  - "external-secrets.io"
                resources: 
                  - "pushsecrets"
                verbs:
                  - "get"
                  - "list"
                  - "create"
                  - "update"
                  - "patch"
              - apiGroups:
                  - ""
                resources:
                  - "secrets"
                  - "configmaps"
                verbs:
                  - "get" 
                  - "list"
                  - "create"
                  - "update"
                  - "patch"
              - apiGroups:
                  - "apps"
                resources:
                  - "deployments"
                verbs:
                  - "get"
                  - "list"
                  - "create"
                  - "update"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
{{ end }}