{{ if .Values.gitlab.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-config
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: "{{ .Values.gitlab.namespace }}"
    server: https://kubernetes.default.svc
  source:
    chart: ansible-sidecar
    targetRevision: "0.1.19"
    repoURL: "https://poc-examples.github.io/charts"
    helm:
      parameters:
        - name: runner.name
          value: gitlab-configure
        - name: runner.namespace
          value: gitlab-system
      valuesObject:
        scope: ClusterRole
        additionalVars:
          domain: apps.{{ .Values.domain }}
        rules:
          - apiGroups:
              - "external-secrets.io"
            resources: 
              - "pushsecrets"
            verbs:
              - "get"
              - "list"
              - "create"
              - "update"
          - apiGroups:
              - ""
            resources:
              - "secrets"
              - "configmaps"
            verbs:
              - "get" 
              - "list"
              - "create"
              - "update"
          - apiGroups:
              - "apps"
            resources:
              - "deployments"
            verbs:
              - "get"
              - "list"
              - "create"
              - "update"

  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}