{{ if .Values.gitlab.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-service
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: "{{ .Values.gitlab.namespace }}"
    server: https://kubernetes.default.svc
  source:
    chart: gitlab
    targetRevision: "8.5.0"
    repoURL: "https://charts.gitlab.io"
    helm:
      valuesObject:
        certmanager:
          install: true
        certmanager-issuer:
          email: admin@openshift.com
        global:
          edition: ce
          hosts:
            domain: apps.{{ .Values.domain }}
        ingress:
          class: none
          annotations:
            route.openshift.io/termination: edge
          configureCertmanager: false
          tls:
            secretName: null
  project: system
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
