{{ if .Values.keycloak.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak-appset
  namespace: "{{ .Values.gitops.namespace }}"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: default
  template:
    metadata:
      name: keycloak-service
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
    spec:
      destination:
        namespace: keycloak
        server: https://kubernetes.default.svc
      source:
        chart: keycloak
        repoURL: "https://poc-examples.github.io/charts"
        targetRevision: "{{ .Values.keycloak.chartVersion }}"
        helm:
          valuesObject:
            domain: "{{ `{{ .metadata.labels.domain }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
{{ end }}
