{{ if .Values.devspaces.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-service
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: devspaces
    server: https://kubernetes.default.svc
  source:
    chart: dev-spaces
    targetRevision: "{{ .Values.devspaces.chartVersion }}"
    repoURL: https://poc-examples.github.io/charts
  project: system
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
