# {{ if .Values.acs.enabled }}
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: tekton-plugin
#   namespace: "{{ .Values.gitops.namespace }}"
# spec:
#   destination:
#     namespace: "openshift-operators"
#     server: https://kubernetes.default.svc
#   source:
#     chart: tekton
#     targetRevision: "{{ .Values.tekton.chartVersion }}"
#     repoURL: "https://poc-examples.github.io/charts"
#     helm:
#       parameters:
#         - name: domain
#           value: "{{ .Values.domain }}"
#   project: plugins
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     managedNamespaceMetadata:
#       labels:
#         argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
#     syncOptions:
#       - CreateNamespace=true
#       - Validate=false
# {{ end }}
