apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollout-controller-appset
  namespace: "{{ .Values.gitops.namespace }}"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
      {{- if .Values.machinesets.enabled }}
        {{- include "MachineSet" . | nindent 16 }}
      {{- end }}
      {{- if .Values.vault.enabled }}
        {{- include "vault" . | nindent 16 }}
      {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ `{{ .syncWave }}` }}"
    spec:
      destination:
        namespace: "{{ .Values.gitlab.namespace }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
        helm:
          valuesObject: {{ `{{ toJson .values }}` }}
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
