apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollout-controller-appset
  namespace: "{{ .Values.gitops.namespace }}"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: default
    - list:
        elements:
{{- if .Values.machinesets.enabled }}
  {{- include "MachineSet" . | nindent 10 }}
{{- end }}
{{- if .Values.vault.enabled }}
  {{- include "vault" . | nindent 10 }}
{{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ .Values.gitlab.namespace }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
        # helm:
        #   valuesObject: {{ `{{ .values }}` }}
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
