{{- define "vault" }}
- application: vault-service
  syncWave: "-6"
  chart: 
    name: machinesets
    url: https://poc-examples.github.io/charts
    version: "{{ .Values.machinesets.chartVersion }}"
  values:
    scope: ClusterRole
    additionalVars:
      domain: "{{ `{{ .metadata.labels.domain }}` }}"
    rules:
      - apiGroups:
          - "external-secrets.io"
        resources: 
          - "pushsecrets"
        verbs:
          - "get"
          - "list"
          - "create"
          - "update"
          - "patch"
      - apiGroups:
          - ""
        resources:
          - "secrets"
          - "configmaps"
        verbs:
          - "get" 
          - "list"
          - "create"
          - "update"
          - "patch"
      - apiGroups:
          - "apps"
        resources:
          - "deployments"
        verbs:
          - "get"
          - "list"
          - "create"
          - "update"
{{- end }}
