{{- if or 
  (and .Values.acs.enabled .Values.acs.enableCapacity)
  (and .Values.acm.enabled .Values.acm.enableCapacity)
  (and .Values.tekton.enabled .Values.tekton.enableCapacity)
  (and .Values.devspaces.enabled .Values.devspaces.enableCapacity)
  (and .Values.quay.enabled .Values.quay.enableCapacity)
  (and .Values.rhoai.enabled .Values.rhoai.enableCapacity)
  (and .Values.amq.enabled .Values.amq.enableCapacity)
}}
{{- $prefix := "" }}
{{- if eq .Values.controller.name "workshop" }}
  {{- $prefix = "workshop-" }}
{{- end }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $prefix }}capacity
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - list:
        elements:
        {{- if (and .Values.acs.enabled .Values.acs.enableCapacity) }}
          - application: acs-capacity
            namespace: acs-capacity
            chart: 
              name: machinesets
              url: https://poc-examples.github.io/charts
              version: "{{ .Values.machinesets.chartVersion }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            values: |
              ansible-runner:
                runner:
                  name: acs-general-capacity
                  namespace: acs-capacity
                  envFrom: []
                additionalVars:
                  machineset: 
                    name: acs-capacity
                    {{- if (eq .Values.cluster.type "aro") }}
                    type: Standard_D8s_v3
                    {{- end }}
                    {{- if or (eq .Values.cluster.type "rosa") (eq .Values.cluster.type "hcp") }}
                    type: Standard_D8s_v3
                    {{- end }}
                    count: 1
        {{- end }}
        {{- if (and .Values.devspaces.enabled .Values.devspaces.enableCapacity) }}
          - application: "{{ $prefix }}devspaces-capacity"
            namespace: devspaces-capacity
            chart: 
              name: machinesets
              url: https://poc-examples.github.io/charts
              version: "{{ .Values.machinesets.chartVersion }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            values: |
              ansible-runner:
                runner:
                  name: devspaces-general-capacity
                  namespace: devspaces-capacity
                  envFrom: []
                additionalVars:
                  machineset: 
                    name: devspaces-capacity
                    type: {{ .Values.devspaces.sku }}
                    count: {{ .Values.devspaces.count }}
        {{- end }}
        {{- if (and .Values.quay.enabled .Values.quay.enableCapacity) }}
          - application: "{{ $prefix }}quay-capacity"
            namespace: quay-capacity
            chart: 
              name: machinesets
              url: https://poc-examples.github.io/charts
              version: "{{ .Values.machinesets.chartVersion }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            values: |
              ansible-runner:
                runner:
                  name: quay-general-capacity
                  namespace: quay-capacity
                  envFrom: []
                additionalVars:
                  machineset: 
                    name: quay-capacity
                    {{- if (eq .Values.cluster.type "aro") }}
                    type: Standard_D8s_v3
                    {{- end }}
                    {{- if or (eq .Values.cluster.type "rosa") (eq .Values.cluster.type "hcp") }}
                    type: Standard_D8s_v3
                    {{- end }}
                    count: 1
        {{- end }}
        {{- if (and .Values.rhoai.enabled .Values.rhoai.enableCapacity) }}
          - application: "{{ $prefix }}rhoai-capacity"
            namespace: rhoai-capacity
            chart: 
              name: machinesets
              url: https://poc-examples.github.io/charts
              version: "{{ .Values.machinesets.chartVersion }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            values: |
              ansible-runner:
                runner:
                  name: rhoai-general-capacity
                  namespace: rhoai-capacity
                  envFrom: []
                additionalVars:
                  machineset: 
                    name: rhoai-capacity
                    {{- if (eq .Values.cluster.type "aro") }}
                    type: Standard_D8s_v3
                    {{- end }}
                    {{- if or (eq .Values.cluster.type "rosa") (eq .Values.cluster.type "hcp") }}
                    type: Standard_D8s_v3
                    {{- end }}
                    count: 1
        {{- end }}
        {{- if (and .Values.amq.enabled .Values.amq.enableCapacity) }}
          - application: "{{ $prefix }}kakfa-capacity"
            namespace: kakfa-capacity
            chart: 
              name: machinesets
              url: https://poc-examples.github.io/charts
              version: "{{ .Values.machinesets.chartVersion }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            values: |
              ansible-runner:
                runner:
                  name: kafka-general-capacity
                  namespace: kakfa-capacity
                  envFrom: []
                additionalVars:
                  machineset: 
                    name: kakfa-capacity
                    type: {{ .Values.amq.sku }}
                    count: {{ .Values.amq.count }}
        {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "https://kubernetes.default.svc"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: capacity
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: {{ `{{ .syncPolicy.automated.prune }}` }}
          selfHeal: {{ `{{ .syncPolicy.automated.selfHeal }}` }}
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
{{- end }}