{{- if or .Values.rhtas.enabled .Values.keycloak.enabled .Values.gatekeeper.enabled .Values.acs.enabled .Values.authorino.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: security
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
              {{- if .Values.gatekeeper.enabled }}
                - application: gatekeeper-service
                  namespace: gatekeeper
                  chart: 
                    name: gatekeeper
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.gatekeeper.chartVersion }}"
              {{- end }}
              {{- if .Values.acs.enabled }}
                - application: advanced-cluster-security-service
                  namespace: rhacs-operator
                  chart: 
                    name: acs
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.acs.chartVersion }}"
              {{- end }}
              {{- if .Values.authorino.enabled }}
                - application: authorino-service
                  namespace: authorino
                  chart: 
                    name: authorino
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.authorino.chartVersion }}"
              {{- end }}
              {{- if .Values.rhtas.enabled }}
                - application: rhtas-service
                  namespace: rhtas
                  chart: 
                    name: rhtas
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.rhtas.chartVersion }}"
                  values: |
                    domain: "{{ `{{ .metadata.labels.domain }}` }}"
              {{- end }}
              {{- if .Values.keycloak.enabled }}
                - application: keycloak-service
                  namespace: keycloak
                  chart: 
                    name: keycloak
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.keycloak.chartVersion }}"
                  values: |
                    domain: {{ `{{ .metadata.labels.domain }}` }}
                    cluster:
                      name: {{ `{{ .metadata.labels.cluster_name }}` }}
                      region: {{ `{{ .metadata.labels.region }}` }}
              {{- end }}
              {{- if .Values.keycloak.enabled }}
                - application: keycloak-post-config
                  namespace: "keycloak"
                  wave: "-1"
                  chart: 
                    name: ansible-runner
                    url: https://poc-examples.github.io/supporting-charts
                    version: "0.2.5"
                  values: |
                    runner:
                      name: keycloak-post-configure
                      namespace: keycloak
                      annotations:
                        argocd.argoproj.io/sync-wave: "0"
                      envFrom:
                        - secretRef:
                            name: rosa-token
                        - secretRef:
                            name: keycloak-client-secret-openshift
                    requirements:
                      collections:
                        - name: bootstrap.post_operator_configuration
                          source: https://github.com/poc-examples/ansible-collections.git#/bootstrap/post_operator_configuration
                          type: git
                          version: main
                          roles:
                            - name: keycloak
                    additionalVars:
                      domain: "{{ `{{ .metadata.labels.domain }}` }}"
                      cluster_name: "{{ `{{ .metadata.labels.cluster_name }}` }}"
                      region: "{{ `{{ .metadata.labels.region }}` }}"
                    rules: []
              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
{{- end }}
