{{- if or .Values.quay_bridge.enabled .Values.gitlab.runners.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: artifacts-config
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
              {{- if .Values.quay_bridge.enabled }}
                - application: quay-bridge-service
                  namespace: "quay-registry"
                  wave: "-2"
                  chart: 
                    name: quay-bridge
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.quay_bridge.chartVersion }}"
                  values: |
                    domain: "{{ `{{ .metadata.labels.domain }}` }}"
                    namespace: "quay-registry"
              {{- end }}
              {{- if .Values.gitlab.runners.enabled }}
                - application: gitlab-runner-service
                  namespace: "{{ .Values.gitlab.namespace }}"
                  wave: "-2"
                  chart: 
                    name: gitlab-runner
                    url: https://charts.gitlab.io
                    version: "0.73.1"
                  values: |
                    gitlabUrl: "https://gitlab.{{ `{{ .metadata.labels.domain }}` }}"
                    serviceAccount:
                      create: true
                    rbac:
                      create: true
                    runners:
                      name: "default"
                      executor: kubernetes
                      secret: runner-secret
                      config: |
                        [[runners]]
                          [runners.kubernetes]
                            namespace = "gitlab-system"
                            image = "ubuntu:22.04"
                            privileged = true
                            service_account = "gitlab-runner-service"
                          [[runners.kubernetes.volumes.secret]]
                            name = "test-org-test-quay-pull-secret"
                            mount_path = "/run/secret"
                            read_only = true
              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ `{{ .wave }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
{{- end }}