apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
              {{- if .Values.machinesets.enabled }}
                - application: machine-sets-manager
                  chart: 
                    name: machinesets
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.machinesets.chartVersion }}"
                  values: |
                    machineset: 
                      enabled: false
                    machinesets:
                      - name: acs
                        machine_type: Standard_D8s_v3
              {{- end }}
              {{- if .Values.vault.enabled }}
                - application: vault-service
                  chart: 
                    name: vault
                    url: https://helm.releases.hashicorp.com
                    version: "{{ .Values.vault.chartVersion }}"
                  values: |
                    csi:
                      enabled: false
                    global:
                      openshift: true
                    injector:
                      enabled: false
                    server:
                      dev:
                        enabled: true
                      enabled: true
                      resources:
                        requests:
                          memory: "128Mi"
                          cpu: "100m"
                        limits:
                          memory: "168Mi"
                          cpu: "150m"
              {{- end }}
              {{- if .Values.external_secrets.enabled }}
                - application: external-secrets-service
                  chart: 
                    name: external_secrets
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.external_secrets.chartVersion }}"
                  values: |
                    namespace: "{{ .Values.external_secrets.namespace }}"
                    gitops:
                      namespace: "{{ .Values.gitops.namespace }}"
                    subscription:
                      channel: stable
              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ .Values.gitlab.namespace }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
        helm:
          values: |
            {{ `{{ .values }}` }}
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
