apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: security
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
              {{- if .Values.gitlab.enabled }}
                - application: gitlab-service
                  namespace: "{{ .Values.gitlab.namespace }}"
                  wave: "-2"
                  chart: 
                    name: gitlab
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.gitlab.chartVersion }}"
                  values: |
                    namespace: "{{ .Values.gitlab.namespace }}"
                    domain: "{{ `{{ .metadata.labels.domain }}` }}"
                    runner:
                      name: gitlab-configure
                      namespace: gitlab-system
                      annotations:
                        argocd.argoproj.io/sync-wave: "3"
                    scope: ClusterRole
                    additionalVars:
                      domain: "{{ `{{ .metadata.labels.domain }}` }}"
                    rules:
                      - apiGroups:
                          - "external-secrets.io"
                        resources: 
                          - "pushsecrets"
                        verbs:
                          - "get"
                          - "list"
                          - "create"
                          - "update"
                          - "patch"
                      - apiGroups:
                          - ""
                        resources:
                          - "secrets"
                          - "configmaps"
                        verbs:
                          - "get" 
                          - "list"
                          - "create"
                          - "update"
                          - "patch"
                      - apiGroups:
                          - "apps"
                        resources:
                          - "deployments"
                        verbs:
                          - "get"
                          - "list"
                          - "create"
                          - "update"
              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ `{{ .wave }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
        helm:
          values: |
            {{ `{{ .values }}` }}
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
