# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: rollout-controller-appset
#   annotations:
#     argocd.argoproj.io/sync-wave: "-3"
# spec:
#   goTemplate: true
#   goTemplateOptions:
#     - "missingkey=error"
#   generators:
#     - matrix:
#         generators:
#           - clusters:
#               selector:
#                 matchLabels:
#                   cluster: default
#           - list:
#               elements:
#               {{- if .Values.serverless.enabled }}
#                 - application: serverless-service
#                   chart: 
#                     name: serverless
#                     url: https://poc-examples.github.io/charts
#                     version: "{{ .Values.serverless.chartVersion }}"
#                   values: ""
#               {{- end }}
#               {{- if .Values.servicemesh.enabled }}
#                 - application: servicemesh-service
#                   chart: 
#                     name: servicemesh
#                     url: https://poc-examples.github.io/charts
#                     version: "{{ .Values.servicemesh.chartVersion }}"
#                   values: ""
#               {{- end }}
#   template:
#     metadata:
#       name: "{{ `{{ .application }}` }}"
#       annotations:
#         argocd.argoproj.io/sync-wave: "{{ `{{ .syncWave }}` }}"
#     spec:
#       destination:
#         namespace: "{{ .Values.gitlab.namespace }}"
#         server: "{{ `{{ .server }}` }}"
#       source:
#         chart: "{{ `{{ .chart.name }}` }}"
#         targetRevision: "{{ `{{ .chart.version }}` }}"
#         repoURL: "{{ `{{ .chart.url }}` }}"
#         helm:
#           values: |
#             {{ `{{ .values }}` }}
#       project: system
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#         managedNamespaceMetadata:
#           labels:
#             argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
#         syncOptions:
#           - CreateNamespace=true
#           - Validate=false
