runner:
  name: "default"
  namespace: "default"
  image: "registry.access.redhat.com/ubi9/python-311:latest"
  env:
    VAULT_TOKEN: placeholder

requirements:
  roles: 
    - repo: "https://github.com/poc-examples/gitlab-role.git"
      name: gitlab

  collections:
    - name: community.kubernetes
      source: "https://galaxy.ansible.com"
    - name: community.okd
      source: "https://galaxy.ansible.com"

additionalVars:
  vault:
    enabled: true
  gitops:
    namespace: "openshift-gitops"

initialJob:
  enabled: true

cron:
  enabled: false
  schedule: "*/30 * * * *"

rules:
  - apiGroups:
      - "external-secrets.io"
    resources: 
      - "pushsecrets"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get" 
      - "list"
      - "create"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get" 
      - "list"
