apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-token
  data:
  - secretKey: ARGOCD_TOKEN
    remoteRef:
      key: argocd
      property: ARGOCD_TOKEN
