apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
  application:
    dynamicPluginsConfigMapName: dynamic-plugins
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: backstage-app-config
        - name: argocd-plugin
      {{- if .Values.gitlab.enabled }}
        - name: gitlab-plugin
      {{- end }}
        - name: kubernetes-plugin
        - name: tech-radar-plugin
        - name: techdocs-plugin
        - name: catalog-config
        - name: dynamic-homepage-plugin
        - name: rbac-conditional-policies
          mountPath: /opt/app-root/src/rbac
        - name: rbac-policies
          mountPath: /opt/app-root/src/rbac
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: SKIP_INTEGRITY_CHECK
          value: "true"
        - name: LOG_LEVEL
          value: info
      secrets:
      {{- if .Values.gitlab.enabled }}
        - name: gitlab-token
          key: GITLAB_TOKEN
      {{- end }}
        - name: keycloak-client-secret-openshift
        - name: credential-keycloak
        - name: postgres-credentials
        - name: backend-credentials
          key: DEVHUB_BACKEND_SECRET
      {{- range .Values.clusters }}
        - name: "{{ .name }}-argocd-token"
          key: "{{ .stage }}_ARGOCD_TOKEN"
      {{- end }}
        - name: service-account-token
          key: token
    extraFiles: 
      mountPath: /opt/app-root/src/extra-files
      configMaps:
        - name: argocd-entities-config
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: {{ .Values.backend.sqlite3.enabled }}
