apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-entities-config
data:
  argocd.yaml: |
    ---
    apiVersion: backstage.io/v1alpha1
    kind: System
    metadata:
      name: argocd-appdev
      description: Collection of ArgoCD Instances used for app dev
    spec:
      owner: cluster-admins
  {{- range .Values.clusters }}
    {{- if ne .role "shared" }}
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: {{ .stage }}
      description: ArgoCD Instance
      tags:
        - argo-instance
    spec:
      type: argo-instance
      lifecycle: {{ .stage }}
      system: argocd-appdev
      owner: cluster-admins
      clusterDomain: {{ .domain }}
      cluster: {{ .name }}
      role: {{ .role }}
    {{- end }}
  {{- end }}
