kind: ConfigMap
apiVersion: v1
metadata:
  name: catalog-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  catalog-config.yaml: |
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API]
      locations:
        - type: url
          target: https://github.com/poc-examples/software-templates/blob/main/catalogs/templates.yaml
      providers:
      {{- if .Values.gitlab.enabled }}
        gitlab:
          selfHosted:
            host: "gitlab.{{ .Values.host }}"
            schedule:
              frequency:
                seconds: 10
              timeout:
                seconds: 60
      {{- end }}
