---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-password
spec:
  length: 20
  symbols: 2
  symbolCharacters: "!@#"
  digits: 4
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "postgres-credentials"
spec:
  refreshInterval: "30m"
  target:
    name: postgres-credentials
    template:
      data:
        POSTGRES_HOST: postgres
        POSTGRES_USER: backstage
        POSTGRES_PORT: 5432
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "postgres-password"
