apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-plugin-cache
  namespace: backstage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem