apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-plugins-root
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: azurefile-csi