## Attempt to abstract this into a catalog Item

# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: self-provisioned-repository
#   namespace: openshift-gitops
#   annotations:
#     argocd.argoproj.io/sync-wave: "-2"
# spec:
#   refreshInterval: "15s"
#   secretStoreRef:
#     name: eso-admin-secret-store
#     kind: ClusterSecretStore
#   target:
#     name: self-provisioned-repository
#     template:
#       metadata:
#         labels:
#           argocd.argoproj.io/secret-type: repository
#       type: generic
#       data:
#         password: "{{`{{ .password }}`}}"
#         username: "root"
#         type: git
#         url: "https://gitlab.apps.{{ .Values.host }}/self-provisioned/manifests.git"
#         insecure: "true"
#         project: system
#   data:
#     - secretKey: "password"
#       remoteRef:
#         key: gitlab
#         property: token
