apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: gitlab-token
  data:
  - secretKey: GITLAB_TOKEN
    remoteRef:
      key: gitlab
      property: group_access_token
