apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: stable-2.10
  installPlanApproval: Automatic
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
