apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.name }}-sp"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: "{{ .Values.targetNamespace }}"
    server: 'https://kubernetes.default.svc'
  source:
    chart: "{{ .Values.chart }}"
    repoURL: "https://poc-examples.github.io/charts"
    targetRevision: "{{ .Values.chartVersion }}"
    helm:
      values: 
        "{{ .Values.helmValues | indent 4 }}"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "openshift-gitops"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - SkipDryRunOnMissingResource=true
