---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password
spec:
  length: 10
  symbols: 0
  digits: 4
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "minio-credentials"
spec:
  refreshInterval: "0"
  target:
    name: minio-credentials
  data:
    - secretKey: MINIO_ROOT_USER
      value: minioadmin
    - secretKey: MINIO_ROOT_PASSWORD
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password