apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "push-secret-minio-credentials"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: eso-admin-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: "minio-credentials"
  data:
    - match:
        secretKey: "MINIO_ROOT_USER"
        remoteRef:
          remoteKey: "minio"
          property: "MINIO_ROOT_USER"
    - match:
        secretKey: "MINIO_ROOT_PASSWORD"
        remoteRef:
          remoteKey: "minio"
          property: "MINIO_ROOT_PASSWORD"