{{- if .Values.k8s }}
{{- if .Values.k8s.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets-store
spec:
  provider:
    kubernetes:
      server:
        url: https://kubernetes.default.svc
      auth:
        serviceAccountRef:
          name: "{{ .Values.k8s.target.serviceaccount }}"
          namespace: "{{ .Values.k8s.target.namespace }}"
{{- end }}
{{- end }}
      auth:
        serviceAccount:
          name: "my-store"