apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "{{ .Values.namespace }}-operatorgroup"
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  targetNamespaces:
    - "{{ .Values.namespace }}"
