apiVersion: rhtas.redhat.com/v1alpha1
kind: Fulcio
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/instance: secure-sign
    app.kubernetes.io/name: secure-sign
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: fulcio
spec:
  certificate:
    commonName: fulcio.apps.{{ .Values.domain}}
    organizationEmail: admin@redhat.com
    organizationName: Red Hat
    # caRef:
    #   name: ca-key-pair
    #   key: ca.crt
    # privateKeyRef:
    #   name: ca-key-pair
    #   key: ca.key
    # privateKeyPasswordRef:
    #   key: passphrase
    #   name: ca-key-pair
  config:
    OIDCIssuers:
      - ClientID: trusted-artifact-signer
        Issuer: 'https://keycloak.apps.{{ .Values.domain}}/realms/tssc'
        IssuerURL: 'https://keycloak.apps.{{ .Values.domain}}/realms/tssc'
        Type: email
  externalAccess:
    enabled: true
  monitoring:
    enabled: false

