apiVersion: rhtas.redhat.com/v1alpha1
kind: Rekor
metadata:
  name: rekor
  labels:
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  namespace: openshift-operators
spec:
  backFillRedis:
    enabled: true
    schedule: 0 0 * * *
  externalAccess:
    enabled: true
  monitoring:
    enabled: false
  pvc:
    retain: true
    size: 5Gi
  rekorSearchUI:
    enabled: true
  signer:
    keyRef:
      key: cosign.privatekey
      name: cosign-keys
    passwordRef:
      key: cosign.password
      name: cosign-keys