apiVersion: batch/v1
kind: CronJob
metadata:
  name: environment-assistant
spec:
  schedule: "0/5 * * * *" # RUN EVERY 5 Minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: environment-assistant
            image: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest
            imagePullPolicy: IfNotPresent
            command:
              - "ansible-playbook"
              - "/etc/ansible/playbook.yml"
            volumeMounts:
              - name: playbook-volume
                mountPath: /etc/ansible  # Mount the playbook inside the container
          restartPolicy: OnFailure
          volumes:
            - name: playbook-volume
              configMap:
                name: ansible-playbook