apiVersion: rhtas.redhat.com/v1alpha1
kind: Tuf
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: tuf
  labels:
    app.kubernetes.io/instance: secure-sign
    app.kubernetes.io/name: secure-sign
    app.kubernetes.io/part-of: trusted-artifact-signer
  namespace: openshift-operators
spec:
  externalAccess:
    enabled: true
    host: tuff.apps.{{ .Values.domain}}
  keys:
    - name: rekor.pub
      secretRef:
        key: public
        name: rekor-public-rekor-j6vtb
    - name: fulcio_v1.crt.pem
      secretRef:
        key: cert
        name: fulcio-cert-fulciolpf85
    - name: ctfe.pub
      secretRef:
        key: public
        name: ctlog-ctlog-keys-2chwx
  port: 80
