backend:
  postgres:
    enabled: true
  sqlite3:
    enabled: false

gitlab:
  enabled: false

github:
  enabled: false

postgres:
  storageClassName: lvms-local

catalogs:
  - https://raw.githubusercontent.com/poc-examples/software-templates/refs/heads/feat-guest-user/catalogs/templates.yaml