apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
  name: quay
spec:
  clusterID: openshift
  credentialsSecret:
    name: quay-credentials
    namespace: "{{ .Values.namespace }}"
  denylistNamespaces:
    - quay-registry
  insecureRegistry: true
  quayHostname: 'https://quay-quay-quay-registry.{{ .Values.domain }}'
  scheduledImageStreamImport: true
