apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.runner.name }}-playbook"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  playbook.yaml: |
    ---
    - name: "Run {{ .Values.runner.name }} Playbook"
      hosts: localhost
      connection: local
      gather_facts: yes
      collections:
      {{- range .Values.requirements.collections }}
        - "{{ .name }}"
      {{- end }}
      vars:
        openshift:
          api_url: "https://kubernetes.default.svc"
          token: "{{ `{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}` }}"
          validate_certs: false
      {{- range $key, $value := .Values.additionalVars }}
        {{ $key }}:
        {{- range $subkey, $subvalue := $value }}
          {{- if eq (typeOf $subvalue) "string" }}
          {{ $subkey }}: "{{ $subvalue }}"
          {{- else if eq (typeOf $subvalue) "bool" }}
          {{ $subkey }}: {{ $subvalue }}
          {{- else }}
          {{ $subkey }}: {{ $subvalue }}
          {{- end }}
        {{- end }}
      {{- end }}
      roles:
      {{- range .Values.requirements.roles }}
        - "{{ .name }}"
      {{- end }}
