apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.runner.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  requirements.yaml: |
    ---
    roles:
    {{- range .Values.requirements.roles }}
      - name: "{{ .name }}"
        src: "{{ .repo }}"
        scm: git
        version: main
        path: "{{ .name }}"
    {{- end }}
    collections:
    {{- range .Values.requirements.collections }}
      - name: "{{ .name }}"
        source: "{{ .source }}"
    {{- end }}

  playbook.yaml: |
    ---
    - name: "Run {{ .Values.runner.name }} Playbook"
      hosts: localhost
      connection: local
      gather_facts: yes
      collections:
      {{- range .Values.requirements.collections }}
        - "{{ .name }}"
      {{- end }}
      vars:
        api_url: "https://kubernetes.default.svc"
        token: "{{ `{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}` }}"
        validate_certs: false
{{ toYaml .Values.additionalVars | indent 8 }}
      roles:
      {{- range .Values.requirements.roles }}
        - "{{ .name }}"
      {{- end }}
