apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  requirements.yaml: |
    ---
    roles:
      - name: "{{ .Values.role }}"
        src: https://github.com/poc-examples/ansible-roles.git
        scm: git
        version: main
        path: bootstrapper-roles/"{{ .Values.role }}"
    collections:
      - name: community.kubernetes
        source: https://galaxy.ansible.com
      - name: community.okd
        source: https://galaxy.ansible.com

  playbook.yaml: |
    ---
    - name: "Run {{ .Values.role }} Role"
      hosts: localhost
      connection: local
      gather_facts: yes
      collections:
        - community.okd
        - community.kubernetes
      vars:
        openshift:
          api_url: "https://kubernetes.default.svc"
          token: "{{ `{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}` }}"
          validate_certs: false

      roles:
        - "{{ .Values.role }}"
