{{ if .Values.cron.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.name }}-job"
spec:
  template:
    spec:
      serviceAccountName: ansible-runner
      containers:
      - name: "{{ .Values.name }}-job"
        image: "{{ .Values.image }}"
        command: ["/bin/bash", "-c"]
        args:
          - |
            pip install ansible;
            pip install openshift;
            ansible-galaxy install -r /etc/ansible/requirements.yaml
            ansible-playbook /etc/ansible/playbook.yaml;
        env:
          {{ toYaml .Values.env }}
      volumeMounts:
      - name: playbook-volume
        mountPath: /etc/ansible
      volumes:
      - name: playbook-volume
        configMap:
          name: "{{ .Values.name }}"
      restartPolicy: Never
{{ end }}