{{ if .Values.initialJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.runner.name }}-job"
spec:
  template:
    spec:
      serviceAccountName: ansible-runner
      containers:
      - name: "{{ .Values.runner.name }}-job"
        image: "{{ .Values.runner.image }}"
        command: ["/bin/bash", "-c"]
        args:
          - |
            pip install ansible;
            pip install openshift;
            ls -la /etc/ansible
            ansible-galaxy install -r /etc/ansible/requirements.yaml
            ansible-playbook /etc/ansible/playbook.yaml;
        env:
{{ toYaml .Values.runner.env | indent 10 }}
        volumeMounts:
        - name: playbook-volume
          mountPath: /etc/ansible
      volumes:
      - name: playbook-volume
        configMap:
          name: "{{ .Values.runner.name }}"
      restartPolicy: Never
{{ end }}