---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.name }}"
rules:
{{- toYaml .Values.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.name }}-binding"
subjects:
- kind: ServiceAccount
  name: ansible-runner
  namespace: "{{ .Values.namespace }}"
roleRef:
  kind: Role
  name: "{{ .Values.name }}"
  apiGroup: rbac.authorization.k8s.io
