---
apiVersion: rbac.authorization.k8s.io/v1
kind: "{{ .Values.scope }}"
metadata:
  name: "{{ .Values.runner.name }}"
rules:
{{- toYaml .Values.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: "{{ .Values.scope }}Binding"
metadata:
  name: "{{ .Values.runner.name }}-binding"
subjects:
- kind: ServiceAccount
  name: ansible-runner
  namespace: "{{ .Values.runner.namespace }}"
roleRef:
  kind: "{{ .Values.scope }}"
  name: "{{ .Values.runner.name }}"
  apiGroup: rbac.authorization.k8s.io
