{{ if .Values.external_secrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  source:
    chart: ansible-sidecar
    repoURL: https://poc-examples.github.io/charts
    targetRevision: "0.1.1"
    helm:
      valuesObject:
        name: "default"
        namespace: "default"
        image: "registry.access.redhat.com/ubi9/python-311:latest"
        role: external-secrets
        initialJob:
          enable: true
        cron:
          enabled: true
          schedule: "*/30 * * * *"
        rules:
          - apiGroups:
              - "external-secrets.io"
            resources: 
              - "pushsecrets"
            verbs:
              - "get"
              - "list"
              - "create"
              - "update"
          - apiGroups:
              - ""
            resources:
              - "secrets"
            verbs:
              - "get" 
              - "list"
              - "create"
          - apiGroups:
              - "apps"
            resources:
              - "deployments"
            verbs:
              - "get" 
              - "list"
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=false
      - Validate=false
{{ end }}
