{{ if .Values.sonarqube.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube-plugin
  namespace: "{{ .Values.gitops.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: "sonarqube"
    server: 'https://kubernetes.default.svc'
  source:
    chart: sonarqube
    repoURL: "https://SonarSource.github.io/helm-chart-sonarqube"
    targetRevision: "{{ .Values.sonarqube.chartVersion }}"
    helm:
      parameters:
        - name: OpenShift.enabled
          value: "true"
        - name: serviceAccount.create
          value: "true"
        - name: postgresql.serviceAccount.enabled
          value: "true"
        - name: route.enabled
          value: "true"
  project: plugins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
    syncOptions:
      - CreateNamespace=true
      - Validate=false
{{ end }}
